In [ ]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
#to check the head of the data set what are the data set we have to check the top secciton of data of head

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
#to check the info of the data set what are the coloums and what are the data types and rows number and count of rows of each columnn etc.....
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3353 non-null   float64
dtypes: category(1), float64(2), int64(4), object(12)
memory usage: 552.6+ KB

In [ ]:
#to check the summary statistics of all the coloum of the dataset of the numerical colounm...
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750051,25.351538
std,1125.977353,15.207589,23.685392,0.713590,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df.describe(include='all')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750051,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.713590,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
#to check the missing values of the data set
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
#This code fills missing values in the Review Rating column by replacing them
#with the median rating of
# the same category, making the dataset more complete while keeping existing
# ratings unchanged.

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

customer_id                  0
age                          0
gender                       0
item_purchased               0
category                     0
purchase_amount              0
location                     0
size                         0
color                        0
season                       0
review_rating                0
subscription_status          0
shipping_type                0
discount_applied             0
previous_purchases           0
payment_method               0
frequency_of_purchases       0
age_group                    0
purchase_frequency_days    547
dtype: int64

In [ ]:
#This code cleans and standardizes column names in your dataset by converting them
 #to lowercase, replacing spaces with underscores, and shortening one column name.
 #Finally, `df.columns` displays all the updated column names. This makes column
 #names more consistent and easier to use in Python.
 # and it end rename the column names

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
#create a column age_group
labels = ['young adult','adult','middle aged','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age','age_group']].head(20)

    age    age_group
0    55  middle aged
1    19  young adult
2    50  middle aged
3    21  young adult
4    45  middle aged
5    46  middle aged
6    63       senior
7    27  young adult
8    26  young adult
9    57  middle aged
10   53  middle aged
11   30  young adult
12   61       senior
13   65       senior
14   64       senior
15   64       senior
16   25  young adult
17   53  middle aged
18   52  middle aged
19   66       senior

In [ ]:
#create a coloumn purchase_frequency-days
# to easily analyze data to convert main data from texxt to numbers for customer behaviors super useful for our analysis

frequency_mapping={
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    "bi Weekly":7,
    'Annually':365,
    'Every 3 Months':90,

}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [ ]:
df[['discount_applied']].head(10)

  discount_applied
0              Yes
1              Yes
2              Yes
3              Yes
4              Yes
5              Yes
6              Yes
7              Yes
8              Yes
9              Yes

In [ ]:
#(df['discount_applied'] == df['promo_code_used']).all() in next ccode and its deleted the promo code is drop

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
from sqlalchemy import create_engine

connection_string = "postgresql://neondb_owner:npg_pClSe1GrZux7@ep-little-dawn-b5mzt3gh-pooler.c-7.us-east-2.aws.neon.tech/customer_behavior?sslmode=require&channel_binding=require"

engine = create_engine(connection_string)

print("Connection engine created!")

Connection engine created!

In [ ]:
table_name = "customers"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print("Dataset uploaded successfully!")

Dataset uploaded successfully!

In [ ]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(
        text("SELECT * FROM customers LIMIT 10")
    )

    for row in result:
        print(row)

(1, 55, 'Male', 'Blouse', 'Clothing', 53, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 14, 'Venmo', 'Fortnightly', 'middle aged', 14.0)
(2, 19, 'Male', 'Sweater', 'Clothing', 64, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 2, 'Cash', 'Fortnightly', 'young adult', 14.0)
(3, 50, 'Male', 'Jeans', 'Clothing', 73, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 23, 'Credit Card', 'Weekly', 'middle aged', 7.0)
(4, 21, 'Male', 'Sandals', 'Footwear', 90, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 49, 'PayPal', 'Weekly', 'young adult', 7.0)
(5, 45, 'Male', 'Blouse', 'Clothing', 49, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 31, 'PayPal', 'Annually', 'middle aged', 365.0)
(6, 46, 'Male', 'Sneakers', 'Footwear', 20, 'Wyoming', 'M', 'White', 'Summer', 2.9, 'Yes', 'Standard', 'Yes', 14, 'Venmo', 'Weekly', 'middle aged', 7.0)
(7, 63, 'Male', 'Shirt', 'Clothing', 85, 'Montana', 'M', 'Gray', 'Fall', 3.2, 'Yes', 'Free Shipping', 'Yes', 49, 'Cash', 'Quarterly', 'senior', 90.0)
(8, 27, 'Male', 'Shorts', 'Clothing', 34, 'Louisiana', 'L', 'Charcoal', 'Winter', 3.2, 'Yes', 'Free Shipping', 'Yes', 19, 'Credit Card', 'Weekly', 'young adult', 7.0)
(9, 26, 'Male', 'Coat', 'Outerwear', 97, 'West Virginia', 'L', 'Silver', 'Summer', 2.6, 'Yes', 'Express', 'Yes', 8, 'Venmo', 'Annually', 'young adult', 365.0)
(10, 57, 'Male', 'Handbag', 'Accessories', 31, 'Missouri', 'M', 'Pink', 'Spring', 4.8, 'Yes', '2-Day Shipping', 'Yes', 4, 'Cash', 'Quarterly', 'middle aged', 90.0)